### ISSUE TITLE
Allow to assign free model IDs to vehicles (increases vehicle slots count)

### ISSUE THREAD

**Issue by oxmaulmike2581** [multitheftauto/mtasa-blue#1010] opened 2019-06-25 21:42 UTC
I think that default vehicles count limit is too small, why nobody didn't want to increase it or allow to use custom ID's like in single player? I think that can be done if define a new Lua function: bool engineAssignModelID ( int modelID ). For example: I want to use free and never used by game model ID №19000 for new vehicle.
``
local id = engineAssignModelID(19000)
local dff = engineReplaceModel(engineLoadDFF("car.dff"), id)
local txd = engineImportTXD(engineLoadTXD("car.txd", true), id)
``
Okay, you can tell me about GTA:SA contains a lot of vehicle slots by default, but huge servers replaces a lot of vehicles, and default limit is not enough.
I read the issue about dynamic seats count, it's good idea if you want to use a lot of 4-door cars.
Why singleplayer users can use up to 1000 vehicle slots with asi plugin, but MTA users not?
Also may allow to set-up vehicle parameters manually or read it from default vehicles IDs (you can choose: set-up all parameters for your vehicles manually (like default handling, wheels size, seats count etc.) or read it from default cars like, for example, admiral, banshee, elegy, etc.)

**Comment by patrikjuvonen** [comment] 2019-06-25 22:26
Duplicate of #869

**Closed as completed by patrikjuvonen** 2019-06-25 22:26 UTC
Labels: enhancement
