### ISSUE TITLE
debugscript returns "debugscript: Your debug mode was set to 0" if using a character value.

### ISSUE THREAD

**Issue by Haxardous** [multitheftauto/mtasa-blue#1322] opened 2020-03-25 15:17 UTC
debugscript will set it's status to "0" whenever typing "debugscript (any *word* character)".

how to reproduce the bug:
1. type /debugscript 1 or 2 or 3 for e.g. (debugscript 3)
2. type /debugscript word for e.g. (debugscript a)
and it'll return "debugscript: Your debug mode was set to 0"

**Comment by PlatinMTA** [comment] 2020-03-25 18:54
I guess this happens bcuz atoi will return 0 in failure to read a number, too lazy to check

Btw I can reproduce the bug

**Comment by qaisjp** [comment] 2020-03-25 19:08
maybe this bug is actually a feature

**Comment by Pirulax** [comment] 2020-05-01 14:56
Im pretty sure its intended, because when you fuck up, you can just type in "debugscript ", then smash ur keyboard, and press enter in the smashing process, and then alt+f4

**Comment by Unde-R** [comment] 2020-08-06 13:26
Dont mind this, I did something wrong.

**Comment by qaisjp** [comment] 2020-08-23 21:10
Fixed in 8f25c22 via #1602

**Closed as completed** 2020-08-30 12:18 UTC
Labels: bug, good first issue
