### ISSUE TITLE
Changing vehicle model can cause network trouble

### ISSUE THREAD

**Issue by lopezloo** [multitheftauto/mtasa-blue#3026] opened 2023-05-21 20:06 UTC
### Describe the bug

Changing vehicle model to vehicle model with max passenger seats count set to `VEHICLE_PASSENGERS_UNDEFINED` (ex. trailers) while player is occuping any passenger seat causes network trouble.

### Steps to reproduce

```lua
run veh = Vehicle(411, 0, 0, 4) me:warpIntoVehicle(veh, 1)
```

```lua
run veh.model = 611
```

### Version

`Multi Theft Auto v1.5.9-release-21630`

### Additional context

1. Not a regression.
2. Similar to issue #2906.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by TracerDS** [comment] 2023-05-22 13:08
Cant reproduce on your version.

This issue is fixed in 1.6

**Closed as completed** 2024-10-13 10:46 UTC
Labels: bug
