### ISSUE TITLE
setPedAimTarget on localPlayer

### ISSUE THREAD

**Issue by Pateeesz** [multitheftauto/mtasa-blue#1441] opened 2020-05-15 15:24 UTC
-

**Comment by Dark-Dragon** [comment] 2020-05-16 02:48
You didn't do the best job filling out the form for feature requests. What is said 'ghetto method'? Have you considered weapon creation and firing through createWeapon and fireWeapon? I know it's not the most convenient to work with since it's client-sided-only and therefore would require a scripting effort to sync it between players, but I think it should be possible in theory. If this is said 'ghetto method' you're referring to, please tell us and maybe add to why you think it wouldn't be suitable for your scenario.

**Comment by Einheit-101** [comment] 2020-05-16 22:06
Duplicate of https://github.com/multitheftauto/mtasa-blue/issues/380

**Comment by StrixG** [comment] 2020-05-16 22:44
Duplicate of #380

**Closed as completed by StrixG** 2020-05-16 22:44 UTC
Labels: enhancement
