### ISSUE TITLE
kickPlayer crashing server while using LatentEvent

### ISSUE THREAD

**Issue by etrnl1337** [multitheftauto/mtasa-blue#2714] opened 2022-08-17 00:44 UTC
### Describe the bug

Use:
https://wiki.multitheftauto.com/wiki/TriggerLatentServerEvent

and in server event just kick client. Boom - server crashed.

That's ridicolous, Such good function makes such problems. Wasted a ton of time for this.

### Steps to reproduce

1. use triggerLatentServerEvent on client side
2. on server side kickPlayer(client)
3. server crashed.

### Version

Client: Multi Theft Auto v1.5.9-release-21261
Server: 1.5.9 R2.1 (build 21238) / Ver: 1.5.9-9.21238.0

sinfo if needed:

Server info for **hidden**
Ver: 1.5.9-9.21238.0
AC: [Allowed client files: None] [Disabled AC: None] [Enabled SD: None]
Voice: Disabled
Glitches: None
Bullet sync weapons: 22,23,24,25,26,27,28,29,30,31,32,33,34
Vehicle extrapolation: Disabled
Tick rates: Plr:100  Cam:500  Ped:400  UnocVeh:400  KeyRot:100  KeyJoy:200
Syncer distances: Ped:100  UnoccupiedVehicle:130 

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment] 2022-08-17 02:05
Duplicate of #2386

**Closed as completed** 2022-08-17 02:05 UTC
Labels: bug, feedback
