### ISSUE TITLE
Crash with multiple screens

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2118] opened 2021-03-12 17:02 UTC
**Describe the bug**
MTA Crashes when you have multiple screens, and disable one that MTA is running on.

**To reproduce**
1. Have two screens
2. Run MTA on one of them
3. Turn off that screen, leave second one running.
4. Wait few seconds.
5. Turn on the screen again - MTA should crash.

**Expected behaviour**
Just stay in background, like when you have single-screen setup.

**Version**
mtasa-1.5.8-rc-20833

**Comment by Allerek** [comment] 2021-03-12 19:52
![image](https://user-images.githubusercontent.com/12304071/110991389-dbae2480-8374-11eb-91b4-7d2865420b05.png)

**Comment by Allerek** [comment] 2021-03-13 12:45
UPDATE:
Can sometimes lead to BSOD, memory leak?

**Comment by patrikjuvonen** [comment] 2021-03-13 13:09
Sounds like a driver issue.

**Comment by Lpsd** [comment] 2021-03-13 16:32
Unable to reproduce

Launch MTA on monitor 1
Turn monitor 1 off
MTA moves automatically to monitor 2
Turn monitor on, no crash and MTA remains on monitor 2

**Comment by FileEX** [comment] 2021-03-14 20:45
Me too unable to reproduce. This issue probably caused by your drivers

**Comment by Lpsd** [comment] 2021-04-06 11:28
Closing issue as it's most likely driver/system related.

If you manage to pinpoint a cause or solution within MTA, please let us know.

**Closed as completed by Lpsd** 2021-04-06 11:28 UTC
Labels: bug
