### ISSUE TITLE
engineRequestModel does not work for the passenger

### ISSUE THREAD

**Issue by httpRick** [multitheftauto/mtasa-blue#2392] opened 2021-10-01 18:49 UTC
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:'
Just start the resource, or replace the vehicle from serverSide using cSide with the ID assigned from engineRequestModel
[requestModel.zip](https://github.com/multitheftauto/mtasa-blue/files/7269466/requestModel.zip)

**Expected behaviour**
We receive network trobules until the resource is restarted or it kicks us out of the server as long as we wait.

**Screenshots**
![mta-screen_2021-10-01_20-47-12](https://user-images.githubusercontent.com/8506863/135671566-83fe9ec9-03d5-4da0-9486-f2fd139b77fe.png)

**Version**
Client Version:
Multi Theft Auto v1.5.9-release-21002
Copyright (C) 2003 - 2021 Multi Theft Auto

Server Version:
MTA:SA Server v 1.5.8-release-20927

**Comment by Xenius97** [comment] 2021-10-01 19:28
#2277
#2166

**Comment by PlatinMTA** [comment] 2021-10-01 20:24
Wait until #2247 is merged or until an alternative arrives.

**Comment by StrixG** [comment] 2021-10-01 21:41
Duplicate of #2166

**Closed as not planned by StrixG** 2021-10-01 21:41 UTC
Labels: bug, feedback
