### ISSUE TITLE
MTA crashes when streamed in object with custom model is deleted (0x000C4BB0)

### ISSUE THREAD

**Issue by Dezash** [multitheftauto/mtasa-blue#2473] opened 2021-12-22 21:02 UTC
**Describe the bug**
When a streamed in custom object, which is allocated by engineRequestModel is deleted due to the resource being stopped, MTA crashes with offset 0x000C4BB0.

**To reproduce**
crun customModel = engineRequestModel("object")
crun pickup = createPickup(me.position.x, me.position.y, me.position.z, 3, customModel)
/reconnect   or  /stop runcode

**Expected behaviour**
No crash

**Version**
Multi Theft Auto v1.5.9-release-21048

**Additional context**
There is a warning in the wiki that custom pickup models can cause crashes, however, I'm posting this anyway as it may be related to some unhandled logic in CClientModelManager.

**Comment by Dutchman101** [comment] 2021-12-22 21:36
It crashes in this GTA function:

```
int __thiscall CBaseModelInfo::RemoveRef(CBaseModelInfo *this)
{
  int v1; // eax
  int result; // eax

  v1 = this->m_nTxdIndex;
  --this->m_nRefCount;
  CTxdStore::RemoveRef(v1);
  return result;
}
```
Something not being cleared? cc @TheNormalnij 

Note: crash offset gta_sa.exe @ 0x000C4BB0 was already a known crash before engineRequestModel got added.. so this is a split cause, another trigger for a crash. Maybe it even tells more about the crash overall, like it's related to pickups in all cases. 

In fact, crash popularity (the 'original', so pre-engineRequestModel) appears to have been bumped by img/model loading tweaks from TheNormalnji along the course of 1.5.8 - it started somewhere shortly before r20779, i mean it's not measurable precisely due to crash stats and the popularity jump for this crash offset relying on the most well-circulated builds, but there are several model loading related changes before that revision, not even just by TheNormalnij (Btw, if it instead wasn't some unknown, bad practise at the top servers from the time of measuring: 95% occured on BS DayZ Ultimate, which now, with the introduction on engineRequestModel and its popularisation amongst servers, has expanded and risen to other servers at the top).. and now, another cause to rise it for engineRequestModel usage significantly dilutes the picture and what we can discover purely by crash stats. You can see im writing a lot of information & unknowns, because our investigation on the previously known main crash is simply unclear and surrounded by questions, but i want to mention as much as possible to better understand this.

It's all to indicate that doing a broader review of that GTA function/MTA's interaction with it, to know all potential reasons/lead ups for this "RemoveRef" crash is a good idea, as it can have split causes up to 3 (like: pre-existing much rarer crash as long as MTA existed.. then IMG/model loading tweaks, in addition to, or exaberated by, engineRequestModel) and that maybe the last 2 rises were caused by TheNormalnji making the same mistake (due to a misconception on how GTA works in that aspect) in his model loading tweaks & engineRequestModel features.

Of course, fixing the main crash with any new knownledge that comes from investigating/debugging this issue here, would be a nice extra catch.

**Comment by PlatinMTA** [comment] 2021-12-22 22:09
Hi.

I have a way to reproduce this crash but it needs some models I am not willing to share at the moment.

Everytime an user stream some big custom models that change the Restricted Area on the Desert, he will instantly crash after disconnecting (even by quitting the game). There is no way arround it that I could find. My guess is that this crash is not related to pickups, but it's only related to the custom models. The user WON'T crash unless he streams this models, or at least is not 100% guaranteed to crash.

This is really common and I think it could be triggered really easy, specially if you have a lot of custom models added to the game.

I could test potential fixes to see if they actually work or at least make it less likely to crash in this circumstances.

**Comment by Dutchman101** [comment] 2021-12-22 22:18
> This is really common

It's the #3 top crash on gta_sa, so yeah. The most widely spread builds get close to 10,000 unique victims of this crash (so possibly multiple, or intermittent, crashes each)

Also, the rise to popularity from higher 1.5.8 revisions on, is clearly distinguishable by crash stats.. as i tried to explain in the confusing comment above. We introduced a bug somewhere, however as i noted it's most likely to have split causes, and the initial rise may have even been explained by that "BS DayZ Ultimate" potential flaw thing. But now, in current builds there is a higher diversity of servers making up the crashes, and it might be clarified by scripters increasingly using engineRequestModel (if 1 of the split causes is in that.. im not saying it can't also be in other things, like the circumstance you mentioned)

Btw, don't hold me to it, but i got a gut feeling about either these: a853ae8, 2b12411
However, there are as i said more model loading/streaming-related changes in the period before that revision of interest i mentioned earlier.. how distant the culprit could be from r20779 isn't pinpointable, as noticing the rise in crash popularity requires well circulated builds.

**Comment by Dezash** [comment] 2021-12-23 18:30
After further testing, it indeed does not appear to be related to pickups. You can reproduce the exact same crash by swapping createPickup with createObject like so:

```
crun customModel = engineRequestModel("object")
crun createObject(customModel, me.position.x, me.position.y, me.position.z)
/reconnect   or  /stop runcode
```

I'll edit the issue title and description accordingly.

EDIT: Doing it with an object does not guarantee a crash like the pickup does

**Comment by TheNormalnij** [comment] 2021-12-25 22:47
I think here is two issues:
1) Reconnect with custom pickups
2) Reconnect when custom object is loaded

First issue can be fixed via #2486
I can't reproduce second issue on default server. Maybe there is additional conditions. @Dezash, can you confirm this?
@PlatinMTA, please, can you build a repro resource with any model from the internet?
Potentially, [my old fix](https://github.com/TheNormalnij/mtasa-blue/tree/TheNormalnij/crash_fix_1840), can help

**Comment by PlatinMTA** [comment] 2021-12-25 23:00
> @PlatinMTA, please, can you build a repro resource with any model from the internet?

I don't think I can, I strongly believe that the crash only occurs with certain models, because this only happens with a custom model I made (but not with others I also made, so I don't really know what makes it crash).

It could be related to the ammount of models I replaced on that place, arround 6~ models where completley replaced. Maybe I would try later to see if I can find a way to reproduce this crash with other models.

**Comment by PlatinMTA** [comment] 2022-01-10 13:37
PR #2486 did not fix the rest of the 0x000C4BB0 crashes. Just in case.

**Comment by Inder00** [comment] 2022-01-10 13:44
Can you attach PoC?

**Closed as completed** 2023-05-01 16:47 UTC
Labels: bug

**Comment by Haxardous** [comment] 2025-04-14 15:07
This crash still occurs 
version: v1.6-release-23142
module: gta_sa.exe
offset: 0x000C4BB0
