### ISSUE TITLE
addCommandHandler return true even when it has not been added

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#706] opened 2018-11-14 14:06 UTC
**Describe the bug**
Some command names can not be used, example `info`, but function still return true

**To reproduce**
Steps to reproduce the behaviour:
```lua
foo = addCommandHandler( "info", function(...)
  iprint("i'm info",...)
end)

bar = addCommandHandler( "infoo", function(...)
  iprint("i'm infoo",...)
end)

iprint("foo?",foo) -- true
iprint("bar?",bar) -- true
```
try use `info` and `infoo` command, `info` not working, `infoo` working

**Expected behaviour**

**Screenshots**

**Version**
Newstest client and server

**Additional context**
/

**Comment by qaisjp** [comment] 2018-11-14 16:27
Duplicate of #418?

**Comment by StifflersMom** [comment] 2018-11-14 16:28
For me, steps to reproduce is showing both commands as working client side with v1.5.6-release-15949

**Closed as completed** 2018-11-14 16:28 UTC
Labels: bug

**Comment by qaisjp** [comment] 2019-08-08 00:16
duplicate of #418
