### ISSUE TITLE
Model streaming issue r21382

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2801] opened 2022-10-28 07:25 UTC
### Describe the bug

Model randomly disappears, restoring to default one. (no restore model function is called)
21378 works fine

### Steps to reproduce

21378: https://streamable.com/yz72qt
21382: https://streamable.com/1236p5

Attach object to player, then detach

### Version

Multi Theft Auto v1.5.9-release-21382

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by vorty123** [comment] 2022-10-28 07:42
![image](https://user-images.githubusercontent.com/12433824/198532092-9ce75729-afa6-4b8d-8d81-e59f628542e1.png)

**Comment by jimz-dev** [comment] 2022-10-28 08:05
Me too
![image](https://user-images.githubusercontent.com/56931445/198536772-3e67e1ab-91a1-4264-9bcd-97e9608b5efb.png)

**Comment by PlatinMTA** [comment] 2022-10-28 08:06
Poor botder lmao

As I stated in the discord, maybe using r21378 isn't safe since it adds a new crash (which was fixed in r21381 afaik). I don't know how that crash works but better to be safe and use r21374 for the time being.

**Comment by jimz-dev** [comment] 2022-10-28 08:15
Did you update new mta version right?

**Comment by audimarley** [comment] 2022-10-28 08:31
it works the first time I enter this version but when I enter again it updates and comes back with the problem again

**Comment by lcloud-aBo09Q** [comment] 2022-10-28 11:53
I can confirm, same issue appearing for players on my server.
Looks like it was pushed out for stable release.

**Comment by ffsPLASMA** [comment] 2022-10-28 12:16
Can confirm, default race pickups wont be replaced either.

https://media.discordapp.net/attachments/897569177362128927/1035517883662467162/gta_sa_Xozi91uKm9.png

**Closed as completed** 2022-10-28 13:51 UTC
Labels: bug

**Comment by botder** [comment] 2022-10-28 15:06
Fix is available in new build: https://nightly.mtasa.com/mtasa-1.5.9-rc-21383-20221028.exe
