### ISSUE TITLE
Make ped respawnable

### ISSUE THREAD

**Issue by thisdp** [multitheftauto/mtasa-blue#1416] opened 2020-04-27 17:16 UTC
**Is your feature request related to a problem? Please describe.**
We can not respawn a dead ped now.
This related to element data sync and network resource taking.
**Describe the solution you'd like**
Make ped respawnable, we can have the same effect as spawnPlayer.

**Comment by qaisjp** [comment] 2020-04-27 18:22
Is this a duplicate of #414?

**Comment by thisdp** [comment] 2020-04-27 18:23
> Is this a duplicate of #414?

spawnPed, instead of destroy and create again.

**Comment by qaisjp** [comment] 2020-04-27 18:28
> instead of destroy and create again

#414 doesn't mention destroying and creating again

**Comment by qaisjp** [comment] 2020-04-27 18:31
Duplicate of #414

**Closed as not planned by qaisjp** 2020-04-27 18:31 UTC
Labels: enhancement
