### ISSUE TITLE
Weird vehicle warps and network trouble lately

### ISSUE THREAD

**Issue by zo3n** [multitheftauto/mtasa-blue#1471] opened 2020-05-27 03:58 UTC
**Describe the bug**
Since I updated to latest nightly, I have been experiencing two issues. One happens randomly and rare, while other one is frequent. Rare one is basically driving around in a (modded) vehicle and after driving for an hour, after jumping or hitting something, it kicks me out of the vehicle like if the vehicle was a bike and i fell of it (that type of kick out) and i get frozen in air with network trouble even though I can talk normally and everything. Killing myself in game resolves the issue with that.

Other more frequent issue is that when I'm glued in freeroam with my vehicle to another (in my case it was infernus glued to hydra), when I'd alt-tab back into game, for my client my player would be in air, and then like 50 ms later it'd warp me back into my actual vehicle. This alt-tab thing would reproduce 100% of time.

It's 6 am now and I haven't slept yet so I don't know perfectly to reproduce these, but this is how I did it and what happened to me. I don't know if latest patches to vehicles by saml1er is related to this, or is it some other issue, because it just started happening with latest nightly.

**To reproduce**
I described in description

**Expected behaviour**
To not happen obviously

**Screenshots**

**Version**
Latest nightly available on 27th May, 2020 6 am (CET), I'll update the issue later I am going to sleep now.

**Comment by Dutchman101** [comment] 2020-05-27 10:01
Hmm, last week i received the following message from the owner of a large server:

> We recently upgraded to a nightly server build (r20555). Now we have global server issues, players randomly not getting unfreezed with setElementFrozen, players can't enter specific cars, and element datas sometimes not being set on vehicles.


I let them try some things, and eventually downgrade to r20551 which resolved it for them.
Not investigated or tested well enough to say it's not something weird on their server that randomly got resolved by reboot to begin with, but if right, then this means it got caused by either:

36efacb
1b14af5
525c920

> I don't know if latest patches to vehicles by saml1er is related to this, or is it some other issue, because it just started happening with latest nightly.

The 'driveby' commits above are unlikely suspects, but they do change sync structures so who knows.
Please test with more nightlies, including [r20551](https://nightly.mtasa.com/mtasa-1.5.7-rc-20551-20200520.exe) that resolved what I described for someone else, and after that go back with steps following [https://buildinfo.mtasa.com/index.php](https://buildinfo.mtasa.com/index.php) until you pinpointed whatever is causing the unclear issues you're describing..

**Comment by qaisjp** [comment] 2020-07-05 10:21
Is this still a problem? There's not been a comment on this in a while. If it's been fixed, which commit fixed it?

**Comment by Pirulax** [comment] 2020-07-05 13:02
I don't think 36efacb3 can cause such a problem.

**Comment by zo3n** [comment] 2020-07-05 19:10
I haven't had network troubles anymore, though I wouldn't close this yet, just to see if anyone else still has this issue

**Comment by qaisjp** [comment] 2020-07-28 18:45
Just one final confirmation @zo3n and I think it's safe to close this.

**Comment by zo3n** [comment] 2020-07-29 10:27
If @Dutchman101 is okay with it (he said he talked with some server owners having these issues as well) then I'm okay as well with closing this, as I haven't encountered it anymore.

**Comment by Dutchman101** [comment] 2020-07-29 10:36
Yes - it was all speculation, and not even the same thing.

**Closed as not planned by Dutchman101** 2020-07-29 10:36 UTC
Labels: bug, invalid
