### ISSUE TITLE
dxGetTextSize returns table instead of two floats

### ISSUE THREAD

**Issue by Inder00** [multitheftauto/mtasa-blue#2072] opened 2021-02-07 12:18 UTC
**Describe the bug**
The [dxGetTextSize](https://wiki.multitheftauto.com/wiki/DxGetTextSize) function from revision 20817 onwards returns a table instead of two floats.

**Expected behaviour**
Return 2 floats ​​as per documentation.

**Comment by patrikjuvonen** [comment] 2021-02-07 12:25
1.5.8 was released in October 2020 which means the documentation is wrong (probably outdated from when it was pushed first to MTA). The changes were made during 2020 but not after the initial release of the function.

Behavior was changed in #1481 and merged July 2020.

Hence, update Wiki.

**Comment by patrikjuvonen** [comment] 2021-02-07 12:27
Closing this as I don't see this being a fault in code but rather outdated documentation.

Updating Wiki now, as well.

**Comment by botder** [comment] 2021-02-07 12:36
> Behavior was changed in #1481 and merged July 2020.

And the old behavior was to return two floats. Added in #935 **Add dxGetTextSize function**.

https://github.com/multitheftauto/mtasa-blue/blob/53019e3ee8dfce60d77267447c18d537a73c47e3/Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp#L900-L904

**Comment by patrikjuvonen** [comment] 2021-02-07 12:38
> > Behavior was changed in #1481 and merged July 2020.
> 
> And the old behavior was to return two floats. Added in #935 **Add dxGetTextSize function**.
> 
> https://github.com/multitheftauto/mtasa-blue/blob/53019e3ee8dfce60d77267447c18d537a73c47e3/Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp#L900-L904

Yes, which is 1.5.8 content and hence was still "unreleased".

**Comment by botder** [comment] 2021-02-07 12:40
And why would a regular non-OOP function return a table if every other function would return two floats in such case?

**Comment by patrikjuvonen** [comment] 2021-02-07 12:40
> And why would a regular non-OOP function return a table if every other function would return two floats in such case?

That's not a bug, that's a feature.

**Comment by botder** [comment] 2021-02-07 12:43
As a scripter you wouldn't expect a non-OOP function to return a Vector2, if you have many other functions doing the exact opposite.

**Comment by patrikjuvonen** [comment] 2021-02-07 12:45
> As a scripter you wouldn't expect a non-OOP function to return a Vector2, if you have many other functions doing the exact opposite.

Fact still remains the function was _released_ returning a Vector2 instead of two floats. The changes made to the function over the course of 1.5.8 development must have taken this _behavior change_ into account, which makes that an intended feature of the function.

If people want it to return two floats under some circumstance, now that is a feature request, not a bug report. I have updated the Wiki page to reflect the current state (the released state) of the function.

**Comment by patrikjuvonen** [comment] 2021-02-07 13:10
As it turns out I was absolutely wrong with this resolution. Sorry for all the inconvenience. My bad, my fault.

Initially released version of the function returns two floats correctly, which should be the way it should work.

**Comment by patrikjuvonen** [comment] 2021-02-07 13:27
We seem to have found the source which is 20817 nightly.

cc @sbx320

**Comment by patrikjuvonen** [comment] 2021-02-20 13:52
Fixed by #2094

**Closed as completed by patrikjuvonen** 2021-02-20 13:52 UTC
Labels: bug
