### ISSUE TITLE
onClientPedsProcessed seems to reset object scaling

### ISSUE THREAD

**Issue by redeibarnabas** [multitheftauto/mtasa-blue#1910] opened 2020-12-08 09:26 UTC
**Describe the bug**
When using setObjectScale and onClientPedsProcessed and attaching it to a bone it seems to reset the the object scaling whenever the event is called.

**Screenshots**
 onClientPedsProcessed
![image](https://user-images.githubusercontent.com/29350278/101464426-ea80d780-393e-11eb-84fc-70f07446b296.png)
 onClientPreRender
![image](https://user-images.githubusercontent.com/29350278/101464710-477c8d80-393f-11eb-8e17-a48f7a31a9d0.png)

**Expected behaviour**
Object scaling should stay the same

**Version**
Multi Theft Auto v1.5.8-release-20751

**Comment by PlatinMTA** [comment] 2020-12-08 09:40
Duplicate of #1836

**Comment by Pirulax** [comment] 2020-12-08 10:29
Duplicate.

**Closed as completed by Pirulax** 2020-12-08 10:29 UTC
Labels: bug

**Comment by qaisjp** [comment] 2020-12-08 11:15
Duplicate of #1836
