### ISSUE TITLE
Multithreading and Parallelism for scripting - Discussion

### ISSUE THREAD

**Issue by LosFaul** [multitheftauto/mtasa-blue#1131] opened 2019-10-21 15:30 UTC
**Is your feature request related to a problem? Please describe.**

Multithreading and beeing able to run scripts parallel is awesome for impvoing script performance.
There are also other many issues that can be solved by having more than one thread availbe.
The problem is there are many concepts on how multithreading could be done that's why I think this should be discussed.

**Describe the solution you'd like**

I think the goal should be to figure out an concept how multithreading can be made availbe to client-side and server-side scripting.
There should also worked out Lua code examples for client-side and server-side.
The examples should also contain ways on how to send/share data between threads.

If this goal is clear then it might be easier for someone to work on a Multithreading feature.

**Comment by Samake** [comment] 2019-10-21 20:06
https://forum.mtasa.com/topic/70236-rel-mta-async-library-multiple-threads-priority-config/

Very good OOP Library with async support:

https://github.com/sbx320/lua_utils

**Comment by qaisjp** [comment] 2019-10-21 20:29
Duplicate of #918

**Closed as completed by qaisjp** 2019-10-21 20:29 UTC
Labels: enhancement
