### ISSUE TITLE
Lighting bug when using mapped objects (replaced objects by script)

### ISSUE THREAD

**Issue by BenhurPaz** [multitheftauto/mtasa-blue#2471] opened 2021-12-22 20:38 UTC
objects created by script don't receive light from sources such as lamppost and cars
![image](https://user-images.githubusercontent.com/52706742/147151968-8270bcb9-c1b5-45a3-9478-1e9b2f3c826c.png)
![image](https://user-images.githubusercontent.com/52706742/147152213-18261420-dc29-4145-b84a-4449eccda9b6.png)
is there any way to fix this problem? by update maybe.

**Comment by lopezloo** [comment] 2021-12-22 20:42
Duplicate of #450.

**Closed as completed** 2021-12-22 20:42 UTC
Labels: bug, feedback
