### ISSUE TITLE
dx functions doesn't work with files that have a space in file name

### ISSUE THREAD

**Issue by LosFaul** [multitheftauto/mtasa-blue#1917] opened 2020-12-14 13:55 UTC
**Describe the bug**

When you have a space in the file name dx functions will throw warnings and doesn't load the image files.

**To reproduce**

make 2 copies an image and name them for example "Test Image.png" and "TestImage.png"
```lua
local file_1 = "Test Image.png"
local file_2 = "TestImage.png"

iprint("fileExists: ", file_1, fileExists(file_1)) --> returns true
iprint("fileExists: ", file_2, fileExists(file_2)) --> returns true

iprint("dxCreateTexture", file_1, dxCreateTexture(file_1)) --> returns nil
iprint("dxCreateTexture", file_2, dxCreateTexture(file_2)) --> returns texture

addEventHandler("onClientRender", root,
    function()
        dxDrawImage(10, 300, 100, 100, file_1) --> doesn't work, warning
        dxDrawImage(120, 300, 100, 100, file_2) --> works
    end
)
```

**Expected behaviour**

dx functions should work with spaces in the file name

**Version**

propably since forever, someone should try to check

**Additional context**

there is also no infomation in wiki that image files with spaces doesn't work for dx functions

**Comment by Unde-R** [comment] 2020-12-14 18:24
Could be because of this maybe:

https://github.com/multitheftauto/mtasa-blue/blob/12cd08bcaff2ff34f38616f6d439b0b0856225f4/Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp#L1009

and between shouldn't this line return false?
```lua
iprint("dxCreateTexture", file_1, dxCreateTexture(file_1)) --> returns nil

**Comment by Dutchman101** [comment] 2020-12-14 22:34
Maybe your script fails because it's trying to use a file that's not a valid texture, as a result of it getting corrupted by issue #1466 (HTTP server cannot handle binary files with a space in filename)

**Comment by LosFaul** [comment] 2020-12-15 09:24
> 
> 
> Maybe your script fails because it's trying to use a file that's not a valid texture, as a result of it getting corrupted by issue #1466 (HTTP server cannot handle binary files with a space in filename)

checked the downloaded client file and you are right
it got corrupted

**Comment by Dutchman101** [comment] 2020-12-15 20:21
Alright then, closing as duplicate of #1466

**Closed as completed by Dutchman101** 2020-12-15 20:21 UTC
Labels: bug

**Comment by StrixG** [comment] 2020-12-15 20:24
Duplicate of #1466
