### ISSUE TITLE
MTA is stuck at 60Hz

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2254] opened 2021-06-05 16:04 UTC
**Describe the bug**
MTA is stuck at 60Hz when fullscreen. This is pretty bad because if you play on 144Hz screen you can see a stutter.

**To reproduce**
Get more than 60 Hz screen, then turn on MTA in FullScreen, the monitor should show its in 60 Hz mode then.
It works fine when in borderless windowed(idk about windowed, but prob same).

**Expected behaviour**
Just unlock the Hz to at least 120. 144 would be cool, but really useless for MTA.

**Version**
Multi Theft Auto v1.5.8-release-20845

**Additional context**
Plz fix.

**Comment by Dutchman101** [comment] 2021-06-05 17:08
> **Additional context**
> Plz fix

It remains to be seen, if it's really that easy (or technically possible) for MTA to fix this for a game from 2005. Even if it appears possible, who knows it will come with a ton of new issues for that reason.

**Comment by StrixG** [comment] 2021-06-05 17:48
Duplicate of #1905

**Closed as not planned by StrixG** 2021-06-05 17:48 UTC
Labels: bug
