### ISSUE TITLE
Forklift bug

### ISSUE THREAD

**Issue by Petya0x44** [multitheftauto/mtasa-blue#1660] opened 2020-09-10 17:59 UTC
If create more 5 vehicle "forklift" (id: 530) then lift don't work. But if you move away from other vehicles, the lift will work.

**Video**
https://www.youtube.com/watch?v=B7dytTnHTjc

**Comment by Einheit-101** [comment] 2020-09-13 22:52
Interesting, does that bug affect other vehicles with special properties aswell? For example Towtruck?

**Comment by lopezloo** [comment] 2021-02-15 18:18
Duplicate of #621

**Closed as not planned by lopezloo** 2021-02-15 18:18 UTC
Labels: bug
