### ISSUE TITLE
Fullscreen bug 1.5.7

### ISSUE THREAD

**Issue by batty098651** [multitheftauto/mtasa-blue#1353] opened 2020-04-06 21:03 UTC
sometimes when you mimize game, in fullscreen mode in standard mode you are unable to return to the game and the only option is to restart it, the error does not only occur with me, but in my case it occurs on every server and i have to play in borderless mode

mtasa forum with the same issue https://forum.mtasa.com/topic/121644-cant-return-to-game-after-minimizing-it/

**Comment by Lpsd** [comment] 2020-04-06 21:05
duplicate of #1103

**Closed as completed by Lpsd** 2020-04-06 21:05 UTC
Labels: bug

**Comment by qaisjp** [comment] 2020-04-06 21:23
Duplicate of #1103
