### ISSUE TITLE
Characters in combination with Alt Gr cannot be created in CEF

### ISSUE THREAD

**Issue by Rob3681** [multitheftauto/mtasa-blue#1422] opened 2020-04-30 17:16 UTC
**Describe the bug**
All characters that are created in combination with Alt Gr can no longer be entered in input/textarea-fields when using CEF. I suspect the problem occurs since one of the last client updates. Some servers use CEF for registration or login windows, in which you can no longer enter an email address because the @ symbol cannot be created on German keyboard. So it can be a serious problem.

**Version**
Multi Theft Auto v1.5.7-release-20447.2

**Comment by qaisjp** [comment] 2020-04-30 17:18
Duplicate of #1303

**Comment by qaisjp** [comment] 2020-04-30 17:18
This was fixed in r20506 - https://buildinfo.mtasa.com/?SHA=245551cc7628593cfe419358d950fb93236bc077

Thank you for the bug report!

**Closed as completed by qaisjp** 2020-04-30 17:18 UTC
Labels: bug

**Comment by Dutchman101** [comment] 2020-04-30 17:24
@Rob3681 just a note: if you want to solve this problem for yourself immediately without waiting for the next MTA release, then download this update: [https://nightly.mtasa.com/?mtasa-1.5-latest](https://nightly.mtasa.com/?mtasa-1.5-latest) (warning: nightlies are test versions and may be unstable)

**Comment by Rob3681** [comment] 2020-04-30 17:50
The main problem is that I, as a server owner, cannot "force" others to use this version. New users currently cannot register because they cannot enter their email address.

I either adjust the registration or I have to wait until the new version is distributed via auto update or max recommended/minclientversion is increased.

But thanks for the quick feedback and sorry for the duplicate.

**Comment by Dutchman101** [comment] 2020-05-01 04:50
> I either adjust the registration or I have to wait until the new version is distributed via auto update or max recommended/minclientversion is increased.

We just bumped it, you can use the build reflected at [https://nightly.mtasa.com/ver/](https://nightly.mtasa.com/ver/) now. I hope it helps

Update @Rob3681: changed it to r20528 to avoid adding untested changes
