### ISSUE TITLE
r20854 broke server side key binds

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#2217] opened 2021-05-03 09:12 UTC
**Describe the bug**
Players using r20854 and above can no longer trigger server side key binds.

**To reproduce**
Can't seem to reproduce this on local server (even tried local server being same as CIT's but different to client) but on CIT various scripts are all failing to work properly with it. For example doing '/afk' to come back from not being AFK there are key binds on the move keys in order to make you no longer AFK, these cause players to be stuck in AFK mode until reconnecting.

r20854 doesn't work.
r20852 works fine:
srun bindKey(getPlayerFromName("[cit]arran"), "mouse2", "down", function(a) outputChatBox("bind works", a) end)
Right clicking makes bind works.

This commit by @patrikjuvonen must be the cause as I see mentions of key bind edits in the commit:
https://github.com/multitheftauto/mtasa-blue/commit/146bd15a87b3391cdedce0cbb3b0e261b1ea457d

**Expected behaviour**
To not be broken.

**Screenshots**

**Version**
Multi Theft Auto v1.5.8-release-20854
MTA:SA Server v1.5.8-release-20863

**Additional context**

**Comment by Dutchman101** [comment] 2021-05-03 10:27
I also encountered it, but the comments regarding it are at [PR 2199](https://github.com/multitheftauto/mtasa-blue/pull/2199#issuecomment-830773309) and may be misplaced if it was caused by 146bd15 instead. Anyways, thanks for adding an issue because i was being lazy

For me it remains as inconsistent as written in that comment.. randomly either happens to any individual serverside bind or not, and still then not all server-side binds are affected. That can be tied to the reason you also couldn't reproduce on a local server, something is influencing the chance to get it.. 

But also, it randomly chooses whether or not to happen on my populated server, without additional script changes inbetween the time it happens and doesn't, just to say it also can't have anything to do with the presence of cursor event in server scripts.

This bug should block the release of 1.5.9

**Comment by Dutchman101** [comment] 2021-05-17 23:47
Fixed in c952054 (more info from PR #2218):

#1978 was reverted in c952054 and we have lightly discussed better solutions to this on Discord.

_Originally posted by @Lpsd in https://github.com/multitheftauto/mtasa-blue/issues/2218#issuecomment-832848946_

**Closed as completed by Dutchman101** 2021-05-17 23:47 UTC
Labels: bug
