### ISSUE TITLE
SWINGING_CHASSIS handling flag has no effect

### ISSUE THREAD

**Issue by KillerHDTR** [multitheftauto/mtasa-blue#1078] opened 2019-09-03 18:14 UTC
**Describe the bug**
SWINGING_CHASSIS handling flag has no effect.

**To reproduce**
1. Spawn Buffalo.
2. Disable SWINGING_CHASSIS flag with *[hedit](/hedit/hedit)*.
3. The car is still shaking.

**Expected behaviour**
SWINGING_CHASSIS should disable/enable swinging vehicle chassis.

**Version**
v1.5.7-release-20550

**Comment by qaisjp** [comment] 2019-09-03 18:15
Please edit / use the template and then this can be re-opened

**Comment by Dutchman101** [comment] 2019-09-03 21:37
For the record, this issue was originally reported at [https://bugs.mtasa.com/view.php?id=6529](https://bugs.mtasa.com/view.php?id=6529) but for some reason wasn't transferred to Github tracker.

**Comment by qaisjp** [comment] 2019-09-03 21:38
> for some reason

we closed most if not all issues that were unverified

**Comment by Dutchman101** [comment] 2020-05-24 09:02
> Disable SWINGING_CHASSIS flag with _[hedit](/hedit/hedit)_.

This script should disable swinging chassis for all vehicles at once:
```lua
local l2s = {[7] = 2, [8] = 3}
for modelID = 400, 611 do
	local flags = getModelHandling(modelID)["handlingFlags"]
	local flagsNum = string.format("%x", flags)
	if l2s[#flagsNum] then
		flagsNum = string.sub(flagsNum, l2s[#flagsNum])
		flagsHex = tonumber("0x" .. flagsNum)
		setModelHandling(modelID, "handlingFlags", flagsHex)
	end
end
```
Makes it easier to reproduce. Btw, read below spoiler for technical details of why it works, it can also be useful after this issue gets fixed (the point it should start working).

<details><summary>Spoiler</summary>
This script would turn off swinging chassis flag for all vehicles, without tampering with other Handling/Model flag values. That is because I found a way to only affect this flag, which would be:
the fact SWINGING_CHASSIS = 0x10000000 which means its register is the leading digit, the highest possible amongst all other handling/model special flags, so by just trimming the leading digit turns the flag off.

Research shows the total offset length can also be 8 digits, in that case this script accounts for it by trimming '10' off the offset.

**Comment by StrixG** [comment] 2020-06-26 15:25
Duplicate of #1117

**Closed as completed by StrixG** 2020-06-26 15:25 UTC
Labels: bug
