### ISSUE TITLE
New argument for weather blending duration in setWeatherBlended function

### ISSUE THREAD

**Issue by LVRENT** [multitheftauto/mtasa-blue#2307] opened 2021-08-13 12:58 UTC
**Is your feature request related to a problem? Please describe.**
As it also says in the wiki, the setWeatherBlended function "_will change the current weather to another in a smooth manner, over the period of 1-2 in-game hours_". I wonder if it's possible to introduce a new argument to let scripters choose their preferred duration and not depending by the game's "1-2 in-game hours". I don't know if it's hardcoded or not.

**Describe the solution you'd like**
To introduce a new argument like "duration" and let scripters to choose their own duration.

**Describe alternatives you've considered**
I don't know at the moment.

**Comment by patrikjuvonen** [comment] 2021-08-13 13:07
Duplicate of https://github.com/multitheftauto/mtasa-blue/issues/1250

**Closed as completed by patrikjuvonen** 2021-08-13 13:07 UTC
Labels: enhancement
