### ISSUE TITLE
Camera clips through objects placed by map editor

### ISSUE THREAD

**Issue by Rartii** [multitheftauto/mtasa-blue#1885] opened 2020-12-01 03:55 UTC
**Describe the bug**

Camera phases through objects placed by the map editor.

**To reproduce**

Drive near any object placed by the map editor and move the camera towards it. It only happens if you go faster than 35 km/h,

**Expected behaviour**

It will ignore the object, the object won't block  the camera movement.

**Screenshots**

![image](https://user-images.githubusercontent.com/47690543/100694853-34424e80-3390-11eb-8e3e-fac985eac9e9.png)
![image](https://user-images.githubusercontent.com/47690543/100694863-3ad0c600-3390-11eb-85b0-866fa88b95a2.png)
https://youtu.be/AExtXlPHD7s

**Version**

v1.5.8-release-20737

**Additional context**

Objects placed by the map editor stop rendering headlight texture.
Original SA object: 
![image](https://user-images.githubusercontent.com/47690543/100695187-feea3080-3390-11eb-9dad-d701d1dbe623.png)
Object placed by the map editor:
![image](https://user-images.githubusercontent.com/47690543/100695233-17f2e180-3391-11eb-8462-a369ec864ede.png)

**Comment by Einheit-101** [comment] 2020-12-01 17:42
Related with
https://github.com/multitheftauto/mtasa-blue/issues/450

**Comment by lopezloo** [comment] 2021-02-15 19:13
Duplicate of #1921

**Closed as not planned by lopezloo** 2021-02-15 19:13 UTC
Labels: bug
