### ISSUE TITLE
Can't change marker alpha for "Arrow" type

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#2230] opened 2021-05-25 09:51 UTC
**Describe the bug**
You can't change the marker alpha with "arrow" marker type

**To reproduce**
Create 'arrow' marker and set alpha argument to 0

**Expected behaviour**
Alpha should working

**Screenshots**
![image](https://user-images.githubusercontent.com/26044224/119477745-85d00280-bd4f-11eb-9afd-9adfc089c8a8.png)

**Version**
1.5.8

**Additional context**

**Comment by PlatinMTA** [comment] 2021-05-25 16:12
Duplicate of #1860

**Closed as not planned** 2021-05-25 16:25 UTC
Labels: bug
