### ISSUE TITLE
Rich Presence still showing even if the option is unchecked

### ISSUE THREAD

**Issue by andreisrw** [multitheftauto/mtasa-blue#1336] opened 2020-03-30 14:52 UTC
**Describe the bug**

Discord Rich Presence still showing if you uncheck the option and reboot your PC.

**Comment by qaisjp** [comment] 2020-04-01 04:33
Marking as 1.6 so that we don't forget. I tested this feature but not on the latest version of the rich presence branch.

Please can someone say if they can reproduce this?

**Comment by PlatinMTA** [comment] 2020-04-02 17:51
Disabling Discord Rich Presence works. Even if you restart the game the rp wont show. Everything works as intended.

I didn't reboot my PC tho, kinda lazy to do that.

Version: v1.5.7-release-20462

**Comment by qaisjp** [comment] 2020-04-02 17:55
Thanks @PlatinMTA. 

@andreisrw - please can you download https://nightly.mtasa.com/mtasa-1.5.7-rc-20477-20200402.exe and tell me if you still have the issue?

**Comment by Simi23** [comment] 2020-04-02 18:43
I tested this on the latest nightly build ([mtasa-1.5.7-rc-20477-20200402.exe](https://nightly.mtasa.com/mtasa-1.5.7-rc-20477-20200402.exe)) and I can confirm the unexpected behaviour. After removing the checkmark in the settings for Rich Presence, the status is removed from Discord but after a game or pc restart (tested both) it shows up again. (Although the checkbox state is correctly saved)

**Comment by qaisjp** [comment] 2020-04-02 18:45
Thank you for testing this! @0x416c69 do you have time to come up with a fix in the next couple of weeks?

**Comment by 0x416c69** [comment] 2020-04-03 07:10
@qaisjp  Well, I will come up with the fix in couple of seconds 😄 

I have no idea why CVars and xml parser module aren't getting loaded as soon as the CCore is constructed (It's on direct3d9 device creation hook) As discord was getting initialized on CCore construction _before_ CVars getting loaded it will result in an undefined behaviour as I didn't initialize the boolean variable.

Anyways, there you go: https://github.com/multitheftauto/mtasa-blue/pull/1345

**Comment by qaisjp** [comment] 2020-04-03 07:15
Thank you!!!

@andreisrw - this will be fixed in tomorrow's build, which you can install **tomorrow** by visiting https://nightly.mtasa.com/?mtasa-1.5.7-latest

**Closed as completed** 2020-04-03 11:37 UTC
Labels: bug
