### ISSUE TITLE
Crash in CRenderWareSA::CreateTexInfo

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#982] opened 2019-06-08 20:41 UTC
**Is your feature request related to a problem? Please describe.**
In some case `CRenderWareSA::CreateTexInfo` function generate a crash

**Describe the solution you'd like**
My investigation:
"m_pTex" is RwTexture and is null
![image](https://user-images.githubusercontent.com/22455534/59152107-fafc7d00-8a3d-11e9-9d55-217295f12adb.png)

stack trace:
![image](https://user-images.githubusercontent.com/22455534/59152117-1c5d6900-8a3e-11e9-966e-9a472a331c2e.png)

Texture name was "helipad_grey1" and is used in this model
https://dev.prineside.com/en/gtasa_samp_model_id/model/9241-copbits_sfn/

**Describe alternatives you've considered**
check if `texTag.m_pTex != nullptr`

**Additional context**
/

**Comment by Dutchman101** [comment] 2019-06-08 20:44
The crash in question is game_sa.dll @ offset 0000f1b3 (at least on r18427) and has a popularity of 10th most common crash on game_sa.

If it means that certain textures can be missing or corrupted (GTA mods), then is there a better way of handling it than a nullptr check, or should it be fixed by MTA to begin with?

**Comment by CrosRoad95** [comment] 2019-06-09 08:04
i found other crash that have same `m_pTex` equal nullptr
![image](https://user-images.githubusercontent.com/22455534/59156558-93761a00-8a9d-11e9-8cef-7cb84ec06d10.png)
![image](https://user-images.githubusercontent.com/22455534/59156573-a8eb4400-8a9d-11e9-8bf8-b1ee673fe7dd.png)

And texture is `sllaelodtunnel` from `lod2lae1.txd`

**Comment by ccw808** [comment] 2019-06-09 23:11
Crash caused by failed memory allocation.
(m_pTex being 0x00000000 is not actually causing the crash, but is a symptom of low memory)

**Closed as completed** 2019-06-12 02:17 UTC
