### ISSUE TITLE
No Anim climb

### ISSUE THREAD

**Issue by bsa11b** [multitheftauto/mtasa-blue#921] opened 2019-05-09 07:15 UTC
There is no anim climb in mta sa 

To reproduce:

1- see anyone climb the build or wall

2- the remote player stuck when climb

Please fix it

**Comment by bsa11b** [comment] 2019-06-29 07:54
up , 2 months and no reply

**Comment by qaisjp** [comment] 2019-06-29 09:18
Duplicate of #1016

**Closed as completed by qaisjp** 2019-06-29 09:18 UTC
Labels: bug
