### ISSUE TITLE
playSound3D plays stream (URL) regardless of distance

### ISSUE THREAD

**Issue by StifflersMom** [multitheftauto/mtasa-blue#1096] opened 2019-09-16 20:57 UTC
**Describe the bug**
playSound3D (url,3000,3000,3000) connects the url of the audio stream and plays the stream, regardless of the max distance (default 20 units)

**To reproduce**

To reproduce you need an audio streaming server like icecast or shoutcast, otherwise you may track the traffic with a network capture. Just place a playSound3D element very far away from the player.

**Expected behaviour**
The audio player should connect to the audio stream server when the player is within the max distance of the sound element.

**Screenshots**

**Version**
Works until 1.5.7-18957 (ok)
v1.5.7-release-19626 and newer are broken.

**Additional context**

**Comment by StifflersMom** [comment] 2019-09-16 21:16
Seems to be fixed in v1.5.7-release-20210

**Comment by ccw808** [comment] 2019-09-16 21:17
@patrikjuvonen Problem caused by bdb80130 (Add client setting to toggle internet sound streams)
Temp fixed by reverting in 59b5fb24

**Comment by Dutchman101** [comment] 2019-09-16 23:05
> @patrikjuvonen Problem caused by [bdb8013](https://github.com/multitheftauto/mtasa-blue/commit/bdb8013029fc22e2d50130516663e14885d0ac4e) (Add client setting to toggle internet sound streams)

should be fixed since e1b7c73

> Seems to be fixed in v1.5.7-release-20210

The only question is if it was properly done

@ccw808

**Comment by ccw808** [comment] 2019-09-17 00:01
This is a new problem. It is caused by [creating the sound](https://github.com/multitheftauto/mtasa-blue/blob/bdb8013029fc22e2d50130516663e14885d0ac4e/Client/mods/deathmatch/logic/CClientSound.cpp#L649) even if it has been streamed out

**Closed as completed** 2019-09-21 09:50 UTC
Labels: bug
