### ISSUE TITLE
setCameraMatrix bug

### ISSUE THREAD

**Issue by borsuczyna** [multitheftauto/mtasa-blue#1462] opened 2020-05-23 17:35 UTC
Hello I found setCameraMatrix bug (look radar, fix is setCameraTarget after resource restart)
video: https://youtu.be/LODogKhtfAM

**Comment by qaisjp** [comment] 2020-05-23 17:39
Please can you provide a simple script to reproduce this?

**Comment by Lpsd** [comment] 2020-05-23 17:39
Please update your issue to follow the [bug report template](https://github.com/multitheftauto/mtasa-blue/issues/new?labels=bug&template=bug_report.md).

Can you provide a basic resource to reproduce the issue?

**Comment by qaisjp** [comment] 2020-05-23 22:35
Duplicate of #1463

**Closed as completed by qaisjp** 2020-05-23 22:35 UTC
Labels: bug
