### ISSUE TITLE
Audio output not working when plugged/re-plugged after MTA launches

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#2909] opened 2023-02-22 16:59 UTC
### Describe the bug

there's no audio when plugging or re-plugging your headphones after starting MTA, even at splash screen
i think the same goes for microphones

### Steps to reproduce

1. start MTA
2. unplug your audio output then plug it again, or plug one if there's none
4. no audio

### Version

v1.5.9-release-21140 (windows 10, 64-bit)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Addlibs** [comment] 2023-02-25 11:01
I've definitely observed this issue with GTASA itself (through the MTA client, not sure if it happens on standalone GTASA too), but not MTASA (though I haven't exactly tested this with the newest client, this is an observation from maybe 3 years ago but I doubt it was addressed); i.e. car engine sounds does not switch when you change output device, and stop working when you unplug the device, but MTA's playSound will still work or switch to the new device.

Related to #1146

**Comment by patrikjuvonen** [comment] 2023-04-10 16:43
Duplicate of #2817

**Closed as not planned by patrikjuvonen** 2023-04-10 16:43 UTC
Labels: bug
