### ISSUE TITLE
DDOS Protection

### ISSUE THREAD

**Issue by talhatugsat** [multitheftauto/mtasa-blue#1976] opened 2021-01-02 15:12 UTC
It would be nice if MTA had cloudflare-like protection system. There would be the main machine where you would set your server up and install resources there. That main machine would only contact to a cloudflare hosted server and users would download from the cloudflare machine without having to directly connect to the main server. I'll attach an example diagram in this post.

There are only 2 downsides of this system:
1) Users might have higher pings
2) Data could be corrupted while in transfer.

But these downsides are nothing compared to the benefits.

Example image: (my extraordinary paint skills)

https://hizliresim.com/FXZXW5

**Comment by patrikjuvonen** [comment] 2021-01-02 15:12
Duplicate of #1975

**Closed as not planned by patrikjuvonen** 2021-01-02 15:12 UTC
Labels: enhancement, invalid
