### ISSUE TITLE
Event: onResourceStateChange

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1458] opened 2020-05-23 12:55 UTC
**Is your feature request related to a problem? Please describe.**
You can't detect when resource change state to eg. failed to load

**Describe the solution you'd like**
add event "onResourceStateChanged" suggested by lopsi

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by Pirulax** [comment] 2020-05-24 01:38
1. Which event should be first called? `onResourceStateChange` or the already existing ones?
2. If `onResourceStateChange` is the first event to be called, gets cancelled(if it can be, only `onResourcePreStart` can be cancelled) should we still call the other event?

My options:
1. `onResourceStateChange`
2. No, we shoudn't, this way the scripter doesnt need to check for `wasCancelled()` when doing stuff in the other event.

@CrosRoad95 @Lpsd

**Comment by Lpsd** [comment] 2020-05-24 19:29
I don’t think it should be cancellable - doesn’t really make any sense imo.

As for the order of events, I don’t think it matters - providing you don’t have poor code design by relying on order of event execution.

Personal preference though I’d go with it being called **after** any other resource related events like onResourceStart.

**Comment by qaisjp** [comment] 2020-05-24 19:37
onResourceStart is currently cancellable. If onResourceStart is cancelled, should onResourceChangeState be triggered?

**Comment by Lpsd** [comment] 2020-05-24 19:41
I’m not entirely familiar with the resource state flow, but I’m assuming it’s:

loaded -> starting -> running

If you cancelled onResourceStart, it should technically never be in the running state, so onResourceStateChange would trigger for “starting” and then “loaded” again once the onResourceStart event has been cancelled.

**Comment by qaisjp** [comment] 2020-05-24 20:05
> I’m not entirely familiar with the resource state flow
> 
> loaded -> starting -> running

Yep that's right https://github.com/multitheftauto/mtasa-blue/issues/798#issuecomment-459737949 - although that flowchart misses what happens with cancelEvent

**Comment by Lpsd** [comment] 2020-05-24 20:11
Yeah I’d have to look into it with regards to cancelEvent.

Either way, if the onResourceStart event is cancelled then onResourceStateChange should be triggered for every state change along the way, aside from “running”.

**Comment by Pirulax** [comment] 2020-05-24 22:43
You mean it shoudnt be triggered for any state change **to** or **from** `running`?

**Comment by Lpsd** [comment] 2020-05-25 11:28
Eh, I’ve thought about it some more and I think we shouldn’t exclude it from triggering based on specific conditions - if the resource state is actually “running” before cancelling onResourceStart (which then changes it to “stopping”) then onResourceStateChange should be triggered for everything

**Comment by Inder00** [comment] 2020-06-22 19:43
test

**Comment by patrikjuvonen** [comment] 2021-09-18 10:00
Duplicate of #995 and fixed in #1651

Create a new issue if you feel there is more to do on the existing event.

**Closed as completed by patrikjuvonen** 2021-09-18 10:00 UTC
Labels: enhancement
