### ISSUE TITLE
It is not possible to apply a shader to the vehiclegrunge256 texture after the latest update.

### ISSUE THREAD

**Issue by ZbyK77** [multitheftauto/mtasa-blue#3894] opened 2024-12-21 16:18 UTC
### Describe the bug

After the latest update (probably “Fix setVehicleDirtLevel (#3837)” r22823), it is no longer possible to apply shaders to the vehiclegrunge256 texture.
This blocks many opportunities for shader use.

### Steps to reproduce

1.  Run example code (Based on shader_tex_names)
`shader = dxCreateShader([[ float4 GetColor() { return float4( 1,0,1, 1 ); } technique tec0 { pass P0 { MaterialEmissive = GetColor(); } } ]])
engineApplyShaderToWorldTexture(shader,"vehiclegrunge*")`
2. Compare the results in the release after 22823 and before 22823.

### Version

Client: Multi Theft Auto v1.6-release-22829 (>22823)
Server: -

### Additional context

r22789
![Image](https://github.com/user-attachments/assets/eb8b4bd8-0827-43b7-b0ba-eadfbc3add51)

r22829
![Image](https://github.com/user-attachments/assets/d6906b9c-42f6-4297-99f7-be18fea4cc3d)

### Relevant log output

```shell
-
```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by tederis** [comment] 2024-12-21 16:29
Duplicate of #3893

**Closed as completed by tederis** 2024-12-21 16:29 UTC
Labels: bug
