### ISSUE TITLE
A function to open an URL on your Default Browser

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#2845] opened 2022-12-22 14:01 UTC
### Is your feature request related to a problem? Please describe.

MTA's browser lacks a lot of functionality. Sometimes a webpage will not work as intended inside an scripted game browser. There should be an option to open your OS's predetermined browser if needed.

The only alternative right now is to ask the users to copy and paste the URL in their browsers, which should be unnecesary.

Mostly this would be a quality of life improvement. Joining discord servers, following in social media, redirecting to forums or webstores should be easier.

We discussed this on the dev. discord, we talked more in detail about this.

### Describe the solution you'd like

```lua
openWebBrowser(string url)
```

This function should ask the user to open their browser with the requested link. They can accept or deny this attempt, just like they can with the in game browser. There should be also an option to disable this type of requests in your client configuration.

**Comment by bum8hj** [comment] 2022-12-22 15:41
It could even have a limit of some sort, to avoid spam, if that's even a concern in the first place. There could also be a 'Do not show again' checkbox in the pop-up.

Edit: RIP in advance 🪦

**Comment by Dutchman101** [comment] 2022-12-22 20:44
Duplicate of #2409 (rejected feature)

**Closed as not planned by Dutchman101** 2022-12-22 20:44 UTC
Labels: enhancement
