### ISSUE TITLE
getVehicleComponentPosition() still returns false for many components

### ISSUE THREAD

**Issue by Einheit-101** [multitheftauto/mtasa-blue#468] opened 2018-09-16 12:36 UTC
**Description**
getVehicleComponentPosition() returns false for (at least) the following components:
headlights, headlights2, taillights, taillights2, engine, exhaust, ped_backseat, ped_frontseat, petrolcap

**Steps to reproduce**
1. Go to map editor, start runcode
2. Get a vehicle like Admiral
3. crun x, y, z = getVehicleComponentPosition(veh, "headlights")
4. crun outputChatBox(x)
5. debug Output = error because x is false

**Expected behavior**
getVehicleComponentPosition() should work for all vehicle dummys/components.

**MTA Version 1.5.6-release-14394**

**Comment by forkerer** [comment] 2018-09-16 12:44
I'm pretty sure that's caused by the fact that those dummies are stored in CVehicleModelInfo object, instead of the vehicle itself, this pull request: https://github.com/multitheftauto/mtasa-blue/pull/390 would give ability to get and set their position.

**Comment by Einheit-101** [comment] 2018-09-16 18:42
Oh, that is true. Nice to see this is going to be available soon. Cant wait to see this PR merged into a nightly.

**Comment by forkerer** [comment] 2018-11-11 21:04
Closing since https://github.com/multitheftauto/mtasa-blue/pull/390 introduced ability to get that.

**Closed as completed by forkerer** 2018-11-11 21:04 UTC
Labels: bug
