### ISSUE TITLE
triggerLatentServerEvent doesn't work sometimes with bandwidth over 16384 bytes

### ISSUE THREAD

**Issue by StrixG** [multitheftauto/mtasa-blue#1140] opened 2019-10-28 13:52 UTC
**Describe the bug**
triggerLatentServerEvent doesn't work sometimes with bandwidth over 16384 bytes.
I think it is related to VS2019 update (https://github.com/multitheftauto/mtasa-blue/commit/b908aa8684b305a5c2fe564e6211c458022eb23d).

**To reproduce**
1. Download [latent_event_test.zip](https://github.com/multitheftauto/mtasa-blue/files/3778904/latent_event_test.zip) and start it.
2. Connect to the server and enter `testevent 16384 3000` in the console. The event will reach the server.
3. Enter `testevent 16385 3000`. Notice the bandwidth is just 1 byte higher.
4. The event will **not** reach the server and it will block all subsequent latent events.

**Expected behaviour**
Latent events should work normally at any speed.

**Version**
Client: Multi Theft Auto v1.5.7-release-20339
Server: MTA:SA Server v1.5.7-release-20320
and
Client: Multi Theft Auto v1.5.7-release-20340
Server: MTA:SA Server v1.5.7-release-20339

**Comment by ccw808** [comment] 2019-10-29 00:12
I can't reproduce this with client & server 1.5.7-release-20339
(Server was Windows 32 bit)

Is the server you tested with Windows or Linux,  32 or 64 bit?

**Comment by StrixG** [comment] 2019-10-29 08:28
Local Windows 10 64 bit and hosted Linux 32 bit.
Can't reproduce this on 20324 client.
20324:
https://youtu.be/xcWB4FLZV2o
20339:
https://youtu.be/6ogCeJa-ibo

**Comment by StrixG** [comment] 2019-10-29 10:14
Eventually, the data reaches the server. But it takes 42 minutes.
![image](https://user-images.githubusercontent.com/8400907/67758126-c0739b00-fa45-11e9-8228-3388cac8f1de.png)
On 20324 it takes less than 5 seconds.

**Comment by ccw808** [comment] 2019-10-31 01:29
Thanks for the videos. Unfortunately, I can't reproduce here, so the bug is intermittent or depends something else.

What is the FPS of the client when you are running the tests?

**Comment by StrixG** [comment] 2019-10-31 12:28
75 FPS in both cases.

**Comment by ccw808** [comment] 2019-11-02 07:05
Please test and show me the video using this modified version of your resource [latent_event_test2.zip](https://github.com/multitheftauto/mtasa-blue/files/3800225/latent_event_test2.zip)

**Comment by StrixG** [comment] 2019-11-02 11:31
20324:
https://youtu.be/lFkBcwthnBg
20340:
https://youtu.be/N2vfVuG2mBc

23 minutes later:
![image](https://user-images.githubusercontent.com/8400907/68070525-4bbb9c00-fd78-11e9-814d-d980309c7a5d.png)

**Comment by dmi7ry** [comment] 2019-11-02 14:43
Actually, once I saw similar behaviour with `triggerServerEvent` for unknown reason (before it, it worked fine for months). Client tried send some data on server (not much, just some short strings as json), but server didn't receive it and then any `triggerServerEvent` didn't work until reconnect. (In my case it was solved using triggerLatentEvent)

**Comment by StrixG** [comment] 2019-11-02 18:19
I can't reproduce this bug when I build MTA with the latest changes on my computer. I can reproduce it only on nightly builds from 20325.

**Comment by ccw808** [comment] 2019-11-02 18:45
@StrixG zip up the client `MTA` folder and upload to https://upload.mtasa.com/

**Comment by StrixG** [comment] 2019-11-02 19:04
https://upload.mtasa.com/u/537553469/MTA.zip_

**Comment by ccw808** [comment] 2019-11-03 04:05
Still can't repro here.

What happens if you try 16385 first?
What happens if you try 16384 two times?
What CPU have you got?

**Comment by StrixG** [comment] 2019-11-03 10:51
I have `Intel Core i5-3570`
Results: https://youtu.be/uS6VOXGjgdE
Also reproducible on another computer with the same processor.

**Comment by ccw808** [comment] 2019-11-05 02:40
Please try latest build 20342

**Comment by StrixG** [comment] 2019-11-05 10:41
The problem is partly gone. Now it's not that slow. But it's still somewhat slower than in 20324 build.
20324: https://youtu.be/kRiMQrT11Cs
20342: https://youtu.be/ZXnrPTWozt0

**Comment by ccw808** [comment] 2019-11-05 17:43
Use the command `shownetstat` and make a video whilst holding the CTRL key

**Comment by StrixG** [comment] 2019-11-05 21:02
20324: https://youtu.be/AG6ac61wZ1Q
20342: https://youtu.be/zk-veJy1fAY

**Comment by ccw808** [comment] 2019-11-05 22:09
Have you got any other resources running?

**Comment by StrixG** [comment] 2019-11-05 22:41
admin, ajax, runcode. These resources affect nothing, just checked it.
Without these resources: https://youtu.be/VfYVMUv1I5Y

**Comment by ccw808** [comment] 2019-11-05 22:56
The `Packets recv/sent` stats are increasing at a much faster rate than expected.
I wonder what is causing that

**Comment by ccw808** [comment] 2019-11-05 23:01
Start `performancebrowser` and using a web browser check:
Performance stats->server->Packet usage

**Comment by StrixG** [comment] 2019-11-05 23:16
![image](https://user-images.githubusercontent.com/8400907/68254286-de875f80-0032-11ea-881c-f330241d13dd.png)

**Comment by ccw808** [comment] 2019-11-05 23:59
In mtaserver.conf, what is `bandwidth_reduction` and the `xxx_sync_intervals` set to?

**Comment by StrixG** [comment] 2019-11-06 00:13
![image](https://user-images.githubusercontent.com/8400907/68256924-3aa1b200-003a-11ea-9a5e-f3a0e0e9b525.png)
Packet usage is less active with default values.

**Comment by ccw808** [comment] 2019-11-06 00:33
Yay, I can reproduce the problem now

**Comment by ccw808** [comment] 2019-11-06 04:23
Fixed in r20343

**Closed as completed by ccw808** 2019-11-06 04:23 UTC
Labels: bug
