### ISSUE TITLE
Crash whilst alt tabbing from MTA to another instance

### ISSUE THREAD

**Issue by R4ven47** [multitheftauto/mtasa-blue#2062] opened 2021-01-31 23:38 UTC
Using 'Standard' screen mode, alt tabbing 2-3 times with an interval of 30-45 seconds leads to game crash, issue has been reported previously but has not been dealt with.

**Comment by patrikjuvonen** [comment] 2021-02-01 00:08
Duplicate of #1103

**Closed as completed by patrikjuvonen** 2021-02-01 00:08 UTC
Labels: bug
