### ISSUE TITLE
Some elements aren't visibles through car windscreen/door windscreen

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-blue#1574] opened 2020-07-22 13:09 UTC
**Describe the bug**
Elements like marker, pickup and DX lines like showcol preview aren't visible through windscreens and door windscreens. I don't know does this is bug MTA or GTA SA.

**To reproduce**

**Expected behaviour**
It's not important bug but i think this should be fixed... Someday

**Screenshots**
![image](https://user-images.githubusercontent.com/26044224/88179961-f0467c80-cc2c-11ea-9ddf-246b7438ffc2.png)

**Version**
1.5.7

**Additional context**

**Comment by Einheit-101** [comment] 2020-07-22 21:28
Duplicate of https://github.com/multitheftauto/mtasa-blue/issues/1367
(That stuff doesnt render btw through a vehicle in general, you will find out when setting vehicle alpha below 255)

**Comment by qaisjp** [comment] 2020-07-23 10:57
Duplicate of #1367

**Closed as completed by qaisjp** 2020-07-23 10:57 UTC
Labels: bug
