### ISSUE TITLE
Can't change weapon if you freeze a ped that's wearing a jetpack

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#531] opened 2018-09-21 12:46 UTC
**Describe the bug**
When a ped gets frozen its jetpack is removed. Now it can't change its weapon until the jetpack is given and removed again.

**To reproduce**
Steps to reproduce the behaviour:
1. create a ped
1. give him weapons
1. set his weapon slot
1. give him jetpack
1. freeze it
1. unfreeze it
1. try to change his weapon (won't work)
1. give him jetpack and remove it again
1. try to change his weapon (will work)

**Expected behaviour**
Changing its weapon should _just work_ without needing a workaround

**Additional context**
Maybe MTA should re-add jetpack after things like frozing, teleporting etc.?

From https://bugs.mtasa.com/view.php?id=8951

**Comment by patrikjuvonen** [comment] 2018-09-21 12:58
Has this issue been reproduced?

I fixed jetpack + freeze issues a short while ago.

**Comment by qaisjp** [comment] 2018-09-21 13:02
Reproduction last checked in 2015

**Comment by patrikjuvonen** [comment] 2018-09-21 13:16
It would help if these get checked before reporting so we don't end up with the same issues of which some probably can't be reproduced. Anyway, self-assigning this.

**Comment by patrikjuvonen** [comment] 2019-01-01 00:02
I am not able to reproduce this problem using the steps provided on Multi Theft Auto v1.5.6-release-16191. This seems to have been completely fixed back when I worked on the jetpack related bugs in #229.

**Closed as not planned by patrikjuvonen** 2019-01-01 00:02 UTC
Labels: invalid
