### ISSUE TITLE
Voice Chat Option To Change Standard Key

### ISSUE THREAD

**Issue by Woesshhh** [multitheftauto/mtasa-blue#856] opened 2019-03-17 14:42 UTC
Problem:
Ok to start, I got a server and i got some problems with the voice chat system. MTA builded a standard key(Z) to talk with others. The problem is that many of my players are from other countries and one of their movement key is Z. I need to help them all one by one to change the key in settings. Every time when a new player comes to the server I need to help him.

Solution:
Please make a setting in mtaserver.conf, so we can change the standard key Z to anything different we like to use in our servers.

Extra Question:
Is it maybe possible to add a setting in mtaserver.conf to enable / disable Push To Talk. This would be nice if this is possible.

**Comment by qaisjp** [comment] 2019-03-17 17:09
We should probably do this on the client, based on the keyboard layout.

**Comment by Loki214** [comment] 2019-03-17 18:03
How about also having the client remember the bindings so you don't have to unbind the default mta binds every time you launch?

**Comment by miusman** [comment] 2019-03-17 19:28
It is a pity that the voice chat button can not be unbinded. Could write like this
```lua
	unbindKey("z", "both", "voiceptt")
	bindKey("b", "down", "voiceptt", "1")
	bindKey("b", "up", "voiceptt", "0")
```

**Comment by Woesshhh** [comment] 2019-03-17 19:33
@miusman First of all, unbindKey will not work because it is a MTA command and it is not added with bindKey.

the bindkeys will work for everybody we need to remove the Z key. We dont need 2 keys for voice chat. Also the players who got problems with z still needs to change their settings.

My solution is the best option in my opinion.

**Comment by qaisjp** [comment] 2019-03-18 17:58
This will be resolved via #857.

**Comment by MrSol0** [comment] 2019-03-20 11:10
for the love of god MTA Team, when can you be like FiveM and both improve the voice chat system and let people change the voice chat bind, in my french keyboard key Z is the walk button, and i don't want to talk when i WALK,.  more than that, voice chat should have local chat voice option like in FiveM, instead of needing to script it, it should be default. so please please fix this issue

**Comment by qaisjp** [comment] 2019-05-21 13:48
this is too big of an annoyance to delay for #857

**Comment by qaisjp** [comment] 2019-05-21 14:13
I've done a bit of exploration and this is what is happening...

**"the bind is always being reset"**

- When MTA loads, it checks for default commands and checks to see if they are bound to at least one key. This checks the arguments as well.
- If you unbind z (`unbind z down voiceptt 1` and `unbind z up voiceptt 0`), but don't add them elsewhere, it will be re-added.
- If you unbind z, and then do `bind ] down voiceptt 1` and `bind ] up voiceptt 0`, `voiceptt` will not be readded to `z`
- If you `unbind z voiceptt`, but then do `bind ] down voiceptt` and `bind ] up voiceptt`, the binds for `z` will be re-added. 

Maybe a special case for `voiceptt` ignoring arguments could be added, but users should probably set `down voiceptt 1` and `up voiceptt 0` properly, instead of doing `bind x down voiceptt` and `bind x up voiceptt`.

**"let people change the voice chat bind"**

I can't reproduce this. Changing the `voiceptt` bind in **Settings -> Binds** works. Both states are being set properly (verified by `binds ]`) and it does not go away after restarting.

This seems to work fine for me, please can you elaborate?

**Comment by qaisjp** [comment] 2020-03-15 00:30
Closing in 24 hours since there seems to be no problem

**Comment by PlatinMTA** [comment] 2020-03-15 00:50
I just want to add that since day one of testing the default voice script (i have two instaces on different servers of mine) I changed the voice key thourgh the config and it never reseted.

**Closed as not planned** 2020-03-15 00:53 UTC
Labels: enhancement, invalid
