### ISSUE TITLE
Add 'forceCursor' to showCursor function

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#2249] opened 2021-05-30 19:39 UTC
**Is your feature request related to a problem? Please describe.**
Yes, for now `showCursor` is resource-dependent, that means - if we have enabled cursor in one resource, and try to disable it in another one it simply just wont work as MTA will detect that cursor was earlier requested by another resource. This can sometimes lead to problems when user is stuck with the cursor on screen, and can't do nothing but reconnect.

**Describe the solution you'd like**
New argument to `showCursor` function called `forceCursor`, which will skip checking if showCursor was requested by another resource, and force cursor to enable/disable anyways.

**Describe alternatives you've considered**
Just remove dependency?

**Additional context**
Pepega

**Comment by FileEX** [comment] 2021-06-07 11:46
Duplicate of https://github.com/multitheftauto/mtasa-blue/issues/891

**Closed as completed** 2021-09-28 13:48 UTC
Labels: enhancement
