### ISSUE TITLE
Add changes to the number of doors for cars that have 2 doors.

### ISSUE THREAD

**Issue by lexa-makeev** [multitheftauto/mtasa-blue#1858] opened 2020-11-21 21:22 UTC
It would be nice to be able to change 2-door cars to 4-door ones. If anyone knows how to do this, I will be glad to hear your comments!

**Comment by Pirulax** [comment] 2020-11-21 21:33
Duplicate of: https://github.com/multitheftauto/mtasa-blue/issues/993 ,please comment if you think otherwise.

**Closed as completed by Pirulax** 2020-11-21 21:33 UTC
Labels: enhancement
