### ISSUE TITLE
Can't jump/use jetpack when you fall into water when entering a vehicle

### ISSUE THREAD

**Issue by MrDadosz** [multitheftauto/mtasa-blue#1680] opened 2020-09-26 10:30 UTC
**Describe the bug**
You can't use jetpack or jump when you fall into water when you're entering a vehicle. You have to teleport player to make it working again.

**To reproduce**
1. fall into water
- you can jump
- you can use jetpack
2. place a vehicle nearby water and make sure that your character will fall into water when you click G
- you can't jump
- you can't use jetpack
- you will have a network trouble for a split second when you teleport
- you can't fix it by toggling jump control

**Screenshots**
https://www.youtube.com/watch?v=3vW-n3wgJIo&feature=youtu.be

**Version**
Multi Theft Auto v1.5.7-release-20632

**Comment by Zangomangu** [comment] 2020-09-27 06:25
The issue seems to be that GTA doesnt interrupt the entering task when you fall into water.
When we enter a vehicle, we initiate the task and wait for GTA to tell us we are either in the vehicle or no longer entering.

This can be fixed by adding a check for whether the ped is in water. 
I can add this but after I submit another PR on enter/exit

**Comment by Woovie** [comment] 2020-10-22 18:54
Duplicate of #521

**Closed as completed by Woovie** 2020-10-22 18:54 UTC
Labels: bug
