### ISSUE TITLE
Vehicle automatically brakes at higher FPS

### ISSUE THREAD

**Issue by EnoNeK** [multitheftauto/mtasa-blue#3072] opened 2023-06-18 08:43 UTC
### Describe the bug

With more FPS (greater than 100) the vehicle begins to brake when you let off the gas.

### Steps to reproduce

1. Set FPS limit above 150
2. Create a vehicle
3. Start driving and then release the gas

### Version

Client: v1.6-release-21852
Server: v1.6-release-21852

Windows 10 - Home

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by xLive** [comment] 2023-06-18 08:47
Duplicate of #2935

**Closed as not planned** 2023-06-18 09:20 UTC
Labels: bug

**Comment by CarlRayanitch** [comment] 2023-06-18 09:37
i don't think this has to do with your topic, but for me to make a realistic handling i first start with a higher weight and mass in handling and it would make it keep going for a long time
